// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using Pomelo.DotNetClient;
using Pomelo;
using NetManager;
using SimpleJson;
using LitJson;
using System.Collections.Generic;




namespace NetManager
{
	public class LoginDataQuickReq
	{
		private const string DEVICE_ID = "deviceID";

		public void GetQuickLoginInf(string deviceID, EventDispatcher.EventCallback eventCallback)
		{
			JsonObject msg = new JsonObject();
			msg[DEVICE_ID] = deviceID;
            ConnectionManager.GetInstance().RequestData<LoginData>(CGNetConst.ROUTE_QUICKLOGIN, msg, eventCallback);
		}
	}
}